USE [P2E]
GO
/****** Object:  Table [dbo].[TB_GRP]    Script Date: 24/07/2019 09:40:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_GRP](
  [CD_GRP] [bigint] IDENTITY(1,1)  NOT NULL,
  [TX_DSC] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TB_GRP] PRIMARY KEY CLUSTERED 
(
  [CD_GRP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_MOD]    Script Date: 24/07/2019 09:40:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_MOD](
  [CD_MOD] [bigint] IDENTITY(1,1) NOT NULL,
  [TX_DSC] [varchar](40) NOT NULL,
 CONSTRAINT [PK_TB_MOD] PRIMARY KEY CLUSTERED 
(
  [CD_MOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_OPR]    Script Date: 24/07/2019 09:40:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_OPR](
  [CD_OPR] [bigint] IDENTITY(1,1) NOT NULL,
  [TX_DSC] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TB_OPR] PRIMARY KEY CLUSTERED 
(
  [CD_OPR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_PAR_NEG]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_PAR_NEG](
  [CD_PAR] [bigint] IDENTITY(1,1) NOT NULL,
  [TXT_RZSOC] [varchar](100) NOT NULL,
  [CNPJ] [varchar](21) NOT NULL,
 CONSTRAINT [PK_TB_PAR_NEG] PRIMARY KEY CLUSTERED 
(
  [CD_PAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_PAR_SRV_MOD]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_PAR_SRV_MOD](
  [CD_PAR_SRV_MOD] [bigint] IDENTITY(1,1)  NOT NULL,
  [CD_PAR] [bigint] NOT NULL,
  [CD_SRV] [bigint] NOT NULL,
  [CD_MOD] [bigint] NOT NULL,
 CONSTRAINT [PK_TB_PAR_SRV_MOD] PRIMARY KEY CLUSTERED 
(
  [CD_PAR_SRV_MOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_ROT]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_ROT](
  [CD_ROT] [bigint] IDENTITY(1,1) NOT NULL,
  [TX_NOME] [varchar](40) NOT NULL,
  [TX_DSC] [varchar](255) NOT NULL,
  [OP_TIPO] [int] NOT NULL,
 CONSTRAINT [PK_TB_ROT] PRIMARY KEY CLUSTERED 
(
  [CD_ROT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_ROT_GRP]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_ROT_GRP](
  [CD_ROT_GRP] [bigint] IDENTITY(1,1) NOT NULL,
  [CD_ROT] [bigint] NOT NULL,
  [CD_GRP] [bigint] NOT NULL,
  [CD_OPR] [bigint] NOT NULL,
 CONSTRAINT [PK_TB_ROT_GRP] PRIMARY KEY CLUSTERED 
(
  [CD_ROT_GRP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_SRV]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_SRV](
  [CD_SRV] [bigint] IDENTITY(1,1) NOT NULL,
  [TXT_DEC] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TB_SRV] PRIMARY KEY CLUSTERED 
(
  [CD_SRV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_USR]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_USR](
  [CD_USR] [bigint] IDENTITY(1,1) NOT NULL,
  [TX_NOME] [varchar](40) NOT NULL,
  [TX_LOGIN] [varchar](40) NOT NULL,
  [TX_SENHA] [varchar](255) NOT NULL,
  [OP_STATUS] [int] NOT NULL,
 CONSTRAINT [PK_TB_USR] PRIMARY KEY CLUSTERED 
(
  [CD_USR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ__TB_USR__3BD12EA04E0ACA48] UNIQUE NONCLUSTERED 
(
  [TX_LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_USR_GRP]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_USR_GRP](
  [CD_USR_GRP] [bigint] IDENTITY(1,1) NOT NULL,
  [CD_USR] [bigint] NOT NULL,
  [CD_GRP] [bigint] NOT NULL,
 CONSTRAINT [PK_TB_USR_GRP] PRIMARY KEY CLUSTERED 
(
  [CD_USR_GRP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_USR_MOD]    Script Date: 24/07/2019 09:40:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_USR_MOD](
  [CD_USR_MOD] [bigint] IDENTITY(1,1) NOT NULL,
  [CD_USR] [bigint] NOT NULL,
  [CD_MOD] [bigint] NOT NULL,
 CONSTRAINT [PK_TB_USR_MOD] PRIMARY KEY CLUSTERED 
(
  [CD_USR_MOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TB_PAR_SRV_MOD]  WITH CHECK ADD  CONSTRAINT [TB_PAR_SRV_MOD_fk0] FOREIGN KEY([CD_PAR])
REFERENCES [dbo].[TB_PAR_NEG] ([CD_PAR])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_PAR_SRV_MOD] CHECK CONSTRAINT [TB_PAR_SRV_MOD_fk0]
GO
ALTER TABLE [dbo].[TB_PAR_SRV_MOD]  WITH CHECK ADD  CONSTRAINT [TB_PAR_SRV_MOD_fk1] FOREIGN KEY([CD_SRV])
REFERENCES [dbo].[TB_SRV] ([CD_SRV])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_PAR_SRV_MOD] CHECK CONSTRAINT [TB_PAR_SRV_MOD_fk1]
GO
ALTER TABLE [dbo].[TB_PAR_SRV_MOD]  WITH CHECK ADD  CONSTRAINT [TB_PAR_SRV_MOD_fk2] FOREIGN KEY([CD_MOD])
REFERENCES [dbo].[TB_MOD] ([CD_MOD])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_PAR_SRV_MOD] CHECK CONSTRAINT [TB_PAR_SRV_MOD_fk2]
GO
ALTER TABLE [dbo].[TB_ROT_GRP]  WITH CHECK ADD  CONSTRAINT [TB_ROT_GRP_fk0] FOREIGN KEY([CD_ROT])
REFERENCES [dbo].[TB_ROT] ([CD_ROT])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_ROT_GRP] CHECK CONSTRAINT [TB_ROT_GRP_fk0]
GO
ALTER TABLE [dbo].[TB_ROT_GRP]  WITH CHECK ADD  CONSTRAINT [TB_ROT_GRP_fk1] FOREIGN KEY([CD_GRP])
REFERENCES [dbo].[TB_GRP] ([CD_GRP])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_ROT_GRP] CHECK CONSTRAINT [TB_ROT_GRP_fk1]
GO
ALTER TABLE [dbo].[TB_ROT_GRP]  WITH CHECK ADD  CONSTRAINT [TB_ROT_GRP_fk2] FOREIGN KEY([CD_OPR])
REFERENCES [dbo].[TB_OPR] ([CD_OPR])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_ROT_GRP] CHECK CONSTRAINT [TB_ROT_GRP_fk2]
GO
ALTER TABLE [dbo].[TB_USR_GRP]  WITH CHECK ADD  CONSTRAINT [TB_USR_GRP_fk0] FOREIGN KEY([CD_USR])
REFERENCES [dbo].[TB_USR] ([CD_USR])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_USR_GRP] CHECK CONSTRAINT [TB_USR_GRP_fk0]
GO
ALTER TABLE [dbo].[TB_USR_GRP]  WITH CHECK ADD  CONSTRAINT [TB_USR_GRP_fk1] FOREIGN KEY([CD_GRP])
REFERENCES [dbo].[TB_GRP] ([CD_GRP])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_USR_GRP] CHECK CONSTRAINT [TB_USR_GRP_fk1]
GO
ALTER TABLE [dbo].[TB_USR_MOD]  WITH CHECK ADD  CONSTRAINT [TB_USR_MOD_fk0] FOREIGN KEY([CD_USR])
REFERENCES [dbo].[TB_USR] ([CD_USR])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_USR_MOD] CHECK CONSTRAINT [TB_USR_MOD_fk0]
GO
ALTER TABLE [dbo].[TB_USR_MOD]  WITH CHECK ADD  CONSTRAINT [TB_USR_MOD_fk1] FOREIGN KEY([CD_MOD])
REFERENCES [dbo].[TB_MOD] ([CD_MOD])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TB_USR_MOD] CHECK CONSTRAINT [TB_USR_MOD_fk1]
GO'