CREATE TABLE [TB_USR] (
	CD_USR bigint NOT NULL,
	TX_NOME varchar(40) NOT NULL,
	TX_LOGIN varchar(40) NOT NULL UNIQUE,
	TX_SENHA varchar(255) NOT NULL,
	OP_STATUS int NOT NULL,
  CONSTRAINT [PK_TB_USR] PRIMARY KEY CLUSTERED
  (
  [CD_USR] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_ROT] (
	CD_ROT bigint NOT NULL,
	TX_NOME varchar(40) NOT NULL,
	TX_DSC varchar(255) NOT NULL,
	OP_TIPO int NOT NULL,
  CONSTRAINT [PK_TB_ROT] PRIMARY KEY CLUSTERED
  (
  [CD_ROT] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_GRP] (
	CD_GRP bigint NOT NULL,
	TX_DSC varchar(100) NOT NULL,
  CONSTRAINT [PK_TB_GRP] PRIMARY KEY CLUSTERED
  (
  [CD_GRP] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_ROT_GRP] (
	CD_ROT_GRP bigint NOT NULL,
	CD_ROT bigint NOT NULL,
	CD_GRP bigint NOT NULL,
	CD_OPR bigint NOT NULL,
  CONSTRAINT [PK_TB_ROT_GRP] PRIMARY KEY CLUSTERED
  (
  [CD_ROT_GRP] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_OPR] (
	CD_OPR bigint NOT NULL,
	TX_DSC varchar(100) NOT NULL,
  CONSTRAINT [PK_TB_OPR] PRIMARY KEY CLUSTERED
  (
  [CD_OPR] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_PAR_NEG] (
	CD_PAR bigint NOT NULL,
	TXT_RZSOC varchar(100) NOT NULL,
	CNPJ varchar(21) NOT NULL,
  CONSTRAINT [PK_TB_PAR_NEG] PRIMARY KEY CLUSTERED
  (
  [CD_PAR] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_MOD] (
	CD_MOD bigint NOT NULL,
	TX_DSC varchar(40) NOT NULL,
  CONSTRAINT [PK_TB_MOD] PRIMARY KEY CLUSTERED
  (
  [CD_MOD] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_SRV] (
	CD_SRV bigint NOT NULL,
	TXT_DEC varchar(100) NOT NULL,
  CONSTRAINT [PK_TB_SRV] PRIMARY KEY CLUSTERED
  (
  [CD_SRV] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_PAR_SRV_MOD] (
	CD_PAR_SRV_MOD bigint NOT NULL,
	CD_PAR bigint NOT NULL,
	CD_SRV bigint NOT NULL,
	CD_MOD bigint NOT NULL,
  CONSTRAINT [PK_TB_PAR_SRV_MOD] PRIMARY KEY CLUSTERED
  (
  [CD_PAR_SRV_MOD] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_USR_MOD] (
	CD_USR_MOD bigint NOT NULL,
	CD_USR bigint NOT NULL,
	CD_MOD bigint NOT NULL,
  CONSTRAINT [PK_TB_USR_MOD] PRIMARY KEY CLUSTERED
  (
  [CD_USR_MOD] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TB_USR_GRP] (
	CD_USR_GRP bigint NOT NULL,
	CD_USR bigint NOT NULL,
	CD_GRP bigint NOT NULL,
  CONSTRAINT [PK_TB_USR_GRP] PRIMARY KEY CLUSTERED
  (
  [CD_USR_GRP] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO



ALTER TABLE [TB_ROT_GRP] WITH CHECK ADD CONSTRAINT [TB_ROT_GRP_fk0] FOREIGN KEY ([CD_ROT]) REFERENCES [TB_ROT]([CD_ROT])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_ROT_GRP] CHECK CONSTRAINT [TB_ROT_GRP_fk0]
GO
ALTER TABLE [TB_ROT_GRP] WITH CHECK ADD CONSTRAINT [TB_ROT_GRP_fk1] FOREIGN KEY ([CD_GRP]) REFERENCES [TB_GRP]([CD_GRP])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_ROT_GRP] CHECK CONSTRAINT [TB_ROT_GRP_fk1]
GO
ALTER TABLE [TB_ROT_GRP] WITH CHECK ADD CONSTRAINT [TB_ROT_GRP_fk2] FOREIGN KEY ([CD_OPR]) REFERENCES [TB_OPR]([CD_OPR])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_ROT_GRP] CHECK CONSTRAINT [TB_ROT_GRP_fk2]
GO





ALTER TABLE [TB_PAR_SRV_MOD] WITH CHECK ADD CONSTRAINT [TB_PAR_SRV_MOD_fk0] FOREIGN KEY ([CD_PAR]) REFERENCES [TB_PAR_NEG]([CD_PAR])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_PAR_SRV_MOD] CHECK CONSTRAINT [TB_PAR_SRV_MOD_fk0]
GO
ALTER TABLE [TB_PAR_SRV_MOD] WITH CHECK ADD CONSTRAINT [TB_PAR_SRV_MOD_fk1] FOREIGN KEY ([CD_SRV]) REFERENCES [TB_SRV]([CD_SRV])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_PAR_SRV_MOD] CHECK CONSTRAINT [TB_PAR_SRV_MOD_fk1]
GO
ALTER TABLE [TB_PAR_SRV_MOD] WITH CHECK ADD CONSTRAINT [TB_PAR_SRV_MOD_fk2] FOREIGN KEY ([CD_MOD]) REFERENCES [TB_MOD]([CD_MOD])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_PAR_SRV_MOD] CHECK CONSTRAINT [TB_PAR_SRV_MOD_fk2]
GO

ALTER TABLE [TB_USR_MOD] WITH CHECK ADD CONSTRAINT [TB_USR_MOD_fk0] FOREIGN KEY ([CD_USR]) REFERENCES [TB_USR]([CD_USR])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_USR_MOD] CHECK CONSTRAINT [TB_USR_MOD_fk0]
GO
ALTER TABLE [TB_USR_MOD] WITH CHECK ADD CONSTRAINT [TB_USR_MOD_fk1] FOREIGN KEY ([CD_MOD]) REFERENCES [TB_MOD]([CD_MOD])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_USR_MOD] CHECK CONSTRAINT [TB_USR_MOD_fk1]
GO

ALTER TABLE [TB_USR_GRP] WITH CHECK ADD CONSTRAINT [TB_USR_GRP_fk0] FOREIGN KEY ([CD_USR]) REFERENCES [TB_USR]([CD_USR])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_USR_GRP] CHECK CONSTRAINT [TB_USR_GRP_fk0]
GO
ALTER TABLE [TB_USR_GRP] WITH CHECK ADD CONSTRAINT [TB_USR_GRP_fk1] FOREIGN KEY ([CD_GRP]) REFERENCES [TB_GRP]([CD_GRP])
ON UPDATE CASCADE
GO
ALTER TABLE [TB_USR_GRP] CHECK CONSTRAINT [TB_USR_GRP_fk1]
GO
