USE [P2E]
GO
/****** Object:  Table [dbo].[TB_AUX_TAB]    Script Date: 24/07/2019 19:09:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_AUX_TAB](
	[TX_TABELA] [varchar](100) NOT NULL,
	[OP_ATIVA] [bit] NOT NULL,
	[CD_TBL_PAI] [varchar](100) NULL,
	[TX_CAMPO_REF] [varchar](100) NULL,
 CONSTRAINT [PK_TB_AUX_TAB] PRIMARY KEY CLUSTERED 
(
	[TX_TABELA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_AUX_VAL]    Script Date: 24/07/2019 19:09:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_AUX_VAL](
	[CD_AUX_VAL] [int] IDENTITY(1,1) NOT NULL,
	[TX_CHAVE] [varchar](100) NOT NULL,
	[TX_VALOR] [varchar](255) NOT NULL,
	[TX_REF] [varchar](100) NULL,
 CONSTRAINT [PK_TB_AUX_VAL] PRIMARY KEY CLUSTERED 
(
	[CD_AUX_VAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TB_AUX_TAB] ADD  CONSTRAINT [DF_TB_AUX_TAB_OP_ATIVA]  DEFAULT ((1)) FOR [OP_ATIVA]
GO
